### ISSUE TITLE
能加点注释么

### ISSUE THREAD

**Issue by 329463417** [zmubai/ZBLM3U8DownLoadTest#1]
代码注释有点少啊 ，看得不是很明白，难过

**Comment by zmubai** [comment]
这个注释确实少了点。 其实这个demo处理的复杂了，不需要多线程的。最好的还是单线程下载。 主要是分几步走：
1.下载m3u8索引文件
2根据索引文件，下载key文件和ts数据文件
3.开启本地服务器，模拟正式环境的视频流形式播放。
欢迎指正哈。demo 里面涉及多线程，测试中 会容易出现死锁，当场也是因为项目提的雕琢需求，最后也没有上。不过还是值得研究的。
