### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by 329463417** [zmubai/ZBLM3U8DownLoadTest#2]
能告诉我下，你从服务器获取M3u8文件是哪个方法吗

**Comment by zmubai** [comment]
//具体代码是这个 通过url向网络下载具体的文本文件。因为这个是操作是耗时操作需要放在异步线程处理
m3u8Str = [[NSString alloc] initWithContentsOfURL:[NSURL URLWithString:urlStr] usedEncoding:0 error:&error];

工程中的路径是：ZBLM3u8Analysiser -》+ (void)analysisWithUrlString:(NSString*)urlStr completaionHandler
